modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

issueTrackerURL="https://github.com/itzme1on/AlcoCraft-Plus/issues"

[[mods]]
modId="alcocraftplus"
version="${file.jarVersion}"
displayName="Alcocraft+"
logoFile="alcocraftplus.png"

displayURL="https://github.com/itzme1on/AlcoCraft-Plus"

credits="Original AlcoCraft mod by hadrus"
authors="itzme1on and contributors from GitHub"
description='''
With this mod you will be able to brew beer and treat your good friends with it!
'''

[[dependencies.alcocraftplus]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.alcocraftplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3]"
    ordering="NONE"
    side="BOTH"